/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.*;

class LibraryTest {
    @Test void rollMethodTEST() {

        // Arrange
        Library sut = new Library();

        //Act
        int[] rolls = sut.rollMethod(4);

        //Assert
        for(int roll : rolls) {
            assertTrue(roll > 0);
        }
        System.out.println(Arrays.toString(rolls));
    }

    @Test void containsDuplicatesMethodTEST() {

        // Had to use google and gpt to understand how to implement testing of my array via a boolean result:

        // Arrange
        Library sut = new Library();
        int[] testArray = {1, 2, 3, 4, 2};
        //Act
        boolean result = sut.containsDuplicatesMethod(testArray);
        //Assert
        assertTrue(result);
        System.out.println(Arrays.toString(testArray));
    }

    @Test void averagingMethodTEST() {

        //Arrange
        Library sut = new Library();
        int[] testArray = {1,2,3,4,5,6};
        //Act
        float result = sut.averagingMethod(testArray);
        //Assert
        assertEquals(3.5, result);
    }

    @Test void arrayAveragerTEST() {

        //Arrange
        Library sut = new Library();
        //Act
        int[] result = sut.arrayAverager();
        int[] returnedArray = {55, 54, 60, 53, 59, 57, 61};
        //Assert
        assertArrayEquals(returnedArray, result);
        System.out.println(Arrays.toString(returnedArray));
    }

    /////////////// LAB 03 ///////////////////

    @Test void weatherArrayMissingTempsTEST() {

        //Arrange
        Library sut = new Library();
        //Act
        int[][] MonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        //Assert
        String expectedResult =
                """
                        High: 72
                        Low: 51
                        Never saw temperature: 63
                        Never saw temperature: 67
                        Never saw temperature: 68
                        Never saw temperature: 69
                        """
                ;
        String result = sut.weatherArrayMissingTemps(MonthTemperatures);
        System.out.println("here are my results: " + result);
        assertEquals(expectedResult,  result);
    }

    @Test
    @DisplayName("Voting Test is as follows:")
    void tallyVoteTEST() {
        //Arrange
        List<String> votes = new ArrayList<>();
        //Act
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        //Assert
        assertEquals("Bush", Library.tally(votes));
        System.out.println("Person with most votes: " +Library.tally(votes));
    }
}
