/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Arrays;

class LibraryTest {
    @Test void rollMethodTEST() {

        // Arrange
        Library sut = new Library();

        //Act
        int[] rolls = sut.rollMethod(4);

        //Assert
        for(int roll : rolls) {
            assertTrue(roll > 0);
        }
        System.out.println(Arrays.toString(rolls));
    }

    @Test void containsDuplicatesMethodTEST() {

        // Had to use google and gpt to understand how to implement testing of my array via a boolean result:

        // Arrange
        Library sut = new Library();
        int[] testArray = {1, 2, 3, 4, 2};
        //Act
        boolean result = sut.containsDuplicatesMethod(testArray);
        //Assert
        assertTrue(result);
    }

    @Test void averagingMethodTEST() {

        //Arrange
        Library sut = new Library();
        int[] testArray = {1,2,3,4,5,6};
        //Act
        float result = sut.averagingMethod(testArray);
        //Assert
        assertEquals(3.5, result);
    }

    @Test void arrayAveragerTEST() {

        //Arrange
        Library sut = new Library();
        //Act
        int[] result = sut.arrayAverager();
        int[] returnedArray = {55, 54, 60, 53, 59, 57, 61};
        //Assert
        assertArrayEquals(returnedArray, result);
        System.out.println(Arrays.toString(returnedArray));
    }
}
