/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {


// I DON'T KNOW WHY WE NEED THIS FILE...CAN I DELETE IT??



//        Restaurant steakEaters = new Restaurant("Steak Eaters", true, 7, 20);
//
//        Review revSteakEaters = new Review("Food bad", "Charles Schwabb", 1.5f, steakEaters);
//        steakEaters.addReview(revSteakEaters);
//
//
//        Restaurant vegEaters = new Restaurant("Veggie Eaters", true, 7, 20);
//
//        Review revVegEaters = new Review("Food good", "Tony Baloni", 3.5f, vegEaters);
//        vegEaters.addReview(revVegEaters);

    }

}
