/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package linter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        jsScannerTool(args);
    }

    // Long story short this was done with tons of help from TA's, Google, Teamwork, and GPT
    public static ArrayList<String> jsScannerTool(String[] args) {
        Path gatesPath = Paths.get("C:\\cmder\\Code401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        System.out.println(gatesPath.toAbsolutePath());

        ArrayList<String> errors = new ArrayList<>();

        try {
            Scanner scanner = new Scanner(Files.newBufferedReader(gatesPath));

            int lineNumber = 1;
            while (scanner.hasNextLine()) {
                String currentLine = scanner.nextLine().trim();
                if (!currentLine.isEmpty() && //https://www.javatpoint.com/java-string-isempty
                        !currentLine.endsWith("{") && //https://www.javatpoint.com/java-string-endswith
                        !currentLine.endsWith("}") &&
                        !currentLine.contains("if") && //https://www.javatpoint.com/java-string-contains
                        !currentLine.contains("else") &&
                        !currentLine.endsWith(";")) {
                    errors.add("Line " + lineNumber + ": Missing semicolon");
                }
                lineNumber++;
            }
        } catch (IOException e) {
        }
        return errors;
    }
}


