/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    @DisplayName("Here is my test")
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
    }
}
