/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void votingCountTEST() {
        App classUnderTest = new App();

        //Will hopefully figure out how to test this. Too tired..
//        ...must sleep...
//        ...darker..
//        ..dark...
//        ...d...
//        ............

    }
}
